name: Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    environment:
      name: test_environment_name
      url: https://spencersteers.com
    steps:
      - uses: actions/checkout@v2
      - id: echo
        run: echo 'touch test ref${{ github.ref }}'
